# Generated by Django 5.1.6 on 2026-03-04 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barbers", "0001_initial"),
        (
            "shops",
            "0003_rename_shops_shop_branch__ea97e2_idx_shops_shop_branch__99bdff_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="barber",
            new_name="barbers_bar_shop_id_3d1b15_idx",
            old_name="barbers_bar_shop_id_8f51d4_idx",
        ),
        migrations.AlterField(
            model_name="barber",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="barber",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="shops.shop",
            ),
        ),
    ]
