# Generated by Django 5.1.6 on 2026-03-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0002_shop_messaging_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="shop",
            new_name="shops_shop_branch__99bdff_idx",
            old_name="shops_shop_branch__ea97e2_idx",
        ),
        migrations.RenameIndex(
            model_name="shop",
            new_name="shops_shop_is_acti_102bcf_idx",
            old_name="shops_shop_is_acti_742785_idx",
        ),
    ]
