# Generated by Django 5.1.6 on 2026-03-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_audit_shop_id_eaa5b8_idx",
            old_name="audit_audit_shop_id_5af66b_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_audit_entity__9535bf_idx",
            old_name="audit_audit_entity__71baf4_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_audit_event_t_ac78f0_idx",
            old_name="audit_audit_event_t_8e8b55_idx",
        ),
        migrations.RenameIndex(
            model_name="securityevent",
            new_name="audit_secur_event_t_08e741_idx",
            old_name="audit_secur_event_t_daa9c2_idx",
        ),
    ]
