# Generated by Django 5.1.6 on 2026-03-04 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_customer_confirmation_fields_and_notification"),
        (
            "shops",
            "0003_rename_shops_shop_branch__ea97e2_idx_shops_shop_branch__99bdff_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="appointment",
            new_name="appointment_shop_id_e9b4df_idx",
            old_name="appointmen_shop_id_40f11d_idx",
        ),
        migrations.RenameIndex(
            model_name="appointment",
            new_name="appointment_shop_id_4b5982_idx",
            old_name="appointmen_shop_id_8cc7b7_idx",
        ),
        migrations.RenameIndex(
            model_name="appointment",
            new_name="appointment_shop_id_53ce38_idx",
            old_name="appointmen_shop_id_bf8fe7_idx",
        ),
        migrations.RenameIndex(
            model_name="appointment",
            new_name="appointment_custome_046536_idx",
            old_name="appointmen_custome_843bb8_idx",
        ),
        migrations.RenameIndex(
            model_name="appointmentnotification",
            new_name="appointment_appoint_ac16da_idx",
            old_name="appointmen_appoint_748f98_idx",
        ),
        migrations.RenameIndex(
            model_name="appointmentnotification",
            new_name="appointment_shop_id_3159bf_idx",
            old_name="appointmen_shop_id_befbca_idx",
        ),
        migrations.RenameIndex(
            model_name="appointmentnotification",
            new_name="appointment_custome_f8155a_idx",
            old_name="appointmen_custome_3d7650_idx",
        ),
        migrations.RenameIndex(
            model_name="customer",
            new_name="appointment_shop_id_c05b91_idx",
            old_name="appointmen_shop_id_36bf62_idx",
        ),
        migrations.RenameIndex(
            model_name="customer",
            new_name="appointment_shop_id_25c6c4_idx",
            old_name="appointmen_shop_id_56b323_idx",
        ),
        migrations.RenameIndex(
            model_name="customer",
            new_name="appointment_shop_id_eae5fa_idx",
            old_name="appointmen_shop_id_9d14d0_idx",
        ),
        migrations.RenameIndex(
            model_name="customer",
            new_name="appointment_shop_id_35ffd5_idx",
            old_name="appointmen_shop_id_90b95a_idx",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="shops.shop",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="shops.shop",
            ),
        ),
    ]
